# Generated by Django 5.1.1 on 2024-09-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100)),
                ('curve_p', models.BigIntegerField()),
                ('curve_a', models.BigIntegerField()),
                ('curve_b', models.BigIntegerField()),
                ('curve_n', models.BigIntegerField()),
                ('g_x', models.BigIntegerField()),
                ('g_y', models.BigIntegerField()),
                ('pubkey_x', models.BigIntegerField()),
                ('pubkey_y', models.BigIntegerField()),
                ('message_x', models.BigIntegerField()),
                ('message_y', models.BigIntegerField()),
                ('c1_x', models.BigIntegerField()),
                ('c1_y', models.BigIntegerField()),
                ('c2_x', models.BigIntegerField()),
                ('c2_y', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SignedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('curve_p', models.IntegerField()),
                ('curve_a', models.IntegerField()),
                ('curve_b', models.IntegerField()),
                ('curve_n', models.IntegerField()),
                ('g_x', models.IntegerField()),
                ('g_y', models.IntegerField()),
                ('message', models.TextField()),
                ('pubkey_x', models.IntegerField()),
                ('pubkey_y', models.IntegerField()),
                ('r', models.IntegerField()),
                ('s', models.IntegerField()),
                ('hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('hashed_password', models.CharField(max_length=128)),
                ('curve_p', models.IntegerField()),
                ('curve_a', models.IntegerField()),
                ('curve_b', models.IntegerField()),
                ('curve_n', models.IntegerField()),
                ('g_x', models.IntegerField()),
                ('g_y', models.IntegerField()),
                ('privkey', models.IntegerField()),
                ('pubkey_x', models.IntegerField()),
                ('pubkey_y', models.IntegerField()),
            ],
        ),
    ]
