# Generated by Django 5.1.1 on 2024-11-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccApp', '0002_encryptedmessage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedmessage',
            name='curve_n',
        ),
    ]
